### install process

In [1]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.22-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.2/63.2 kB 9.4 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.0 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from yfinance) (2.0.1)
Requirement already satisfied: numpy>=1.16.5 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from yfinance) (1.23.5)
Requirement already satisfied: requests>=2.26 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from yfinance) (2.28.2)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Collecting lxml>=4.9.1 (from yfinance)
  Downloading lxml-4.9.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 88.6 MB/s eta 0:00:00:00:0100:01
Collecting appdirs>=1.4.4 (from yfinance)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pytz>=2022.5 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from yfinance) (2023.3)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.3.8-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.8/114.8 kB 24.9 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from yfinance) (4.12.2)
Collecting html5lib>=1.1 (from yfinance)
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: soupsieve>1.2 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.2.post1)
Requirement already satisfied: six>=1.9 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from requests>=2.26->yfinance) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from requests>=2.26->yfinance) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from requests>=2.26->yfinance) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /home/jacky/miniconda2/envs/jacky/lib/python3.9/site-packages (from requests>=2.26->yfinance) (2022.12.7)
Installing collected packages: multitasking, appdirs, lxml, html5lib, frozendict, yfinance
Successfully installed appdirs-1.4.4 frozendict-2.3.8 html5lib-1.1 lxml-4.9.2 multitasking-0.0.11 yfinance-0.2.22

In [27]:
import yfinance as yf

# Define the ticker symbol for the stock you want to fetch data for
ticker_symbol = "TEMN.SW"

# Fetch historical stock price data
data = yf.download(ticker_symbol, start="2020-01-01", end="2023-06-28")

[*********************100%***********************]  1 of 1 completed

In [28]:
data

                  Open        High         Low       Close   Adj Close  Volume
Date
2020-01-03  153.100006  154.000000  151.550003  153.600006  147.812164  274068
2020-01-06  152.350006  153.300003  151.100006  153.300003  147.523468  225145
2020-01-07  153.850006  156.500000  151.500000  151.500000  145.791321  268437
2020-01-08  151.100006  153.000000  149.500000  152.850006  147.090439  245846
2020-01-09  154.000000  155.949997  152.800003  155.149994  149.303757  280922
...                ...         ...         ...         ...         ...     ...
2023-06-21   71.139999   71.540001   69.820000   70.260002   70.260002  215430
2023-06-22   69.860001   70.260002   69.459999   70.180000   70.180000  124855
2023-06-23   69.820000   70.099998   68.680000   69.160004   69.160004  168352
2023-06-26   69.000000   69.639999   67.980003   68.720001   68.720001  207825
2023-06-27   69.080002   69.120003   68.260002   68.559998   68.559998  112393

[881 rows x 6 columns]

In [15]:
import yfinance as yf

msft = yf.Ticker("TEMN.SW")

# get all stock info
msft.info

# get historical market data
hist = msft.history(period="1mo")

# show meta information about the history (requires history() to be called first)
msft.history_metadata

# show actions (dividends, splits, capital gains)
msft.actions
msft.dividends
msft.splits
msft.capital_gains  # only for mutual funds & etfs

# show share count
msft.get_shares_full(start="2023-01-01", end=None)

# show financials:
# - income statement
msft.income_stmt
msft.quarterly_income_stmt
# - balance sheet
msft.balance_sheet
msft.quarterly_balance_sheet
# - cash flow statement
msft.cashflow
msft.quarterly_cashflow
# see `Ticker.get_income_stmt()` for more options

# show holders
msft.major_holders
msft.institutional_holders
msft.mutualfund_holders

# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
msft.earnings_dates

# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
msft.isin

# show options expirations
msft.options

# show news
msft.news

[{'uuid': 'b06112fb-e73b-372a-b2fa-b96b13aa7ea1',
  'title': 'Q3 2023 Micron Technology Inc Post Earnings Analyst Call Earnings Call',
  'publisher': 'Thomson Reuters StreetEvents',
  'link': 'https://finance.yahoo.com/news/q3-2023-micron-technology-inc-115513694.html',
  'providerPublishTime': 1688039713,
  'type': 'STORY',
  'relatedTickers': ['MU']},
 {'uuid': '1afbfefb-dce2-3e81-bf1a-827f8c90e45d',
  'title': 'Morning News Call - Canada, June 29',
  'publisher': 'Reuters',
  'link': 'https://finance.yahoo.com/news/morning-news-call-canada-june-115405334.html',
  'providerPublishTime': 1688039645,
  'type': 'STORY'},
 {'uuid': '0ffbc301-7f48-30b8-ba3b-4ab751992984',
  'title': 'SPCE Stock Rockets Ahead Of Virgin Galactic Launch; How To Watch The Commercial Space Flight',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/0ffbc301-7f48-30b8-ba3b-4ab751992984/spce-stock-rockets-ahead-of.html',
  'providerPublishTime': 1688039508,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/P86cz9139cY1g9o3RaSrvg--~B/aD01NzI7dz0xMDEyO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/90ae9007652fb09e8101dc6e45dd05ba',
     'width': 1012,
     'height': 572,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/8Ww4.8iRv2vusrjW9Wwgbw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/90ae9007652fb09e8101dc6e45dd05ba',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['SPCE']},
 {'uuid': '9b6def12-4ba7-314c-a46b-169d5161a961',
  'title': 'EU-funded hybrid car prototype explodes in Italy, killing two people',
  'publisher': 'Reuters',
  'link': 'https://finance.yahoo.com/news/eu-funded-hybrid-car-prototype-115101705.html',
  'providerPublishTime': 1688039461,
  'type': 'STORY'},
 {'uuid': '56723767-0234-3bc4-af3a-106f23b2e505',
  'title': 'Virgin Galactic to Launch First Commercial Spaceflight After Setbacks, Delays',
  'publisher': 'The Wall Street Journal',
  'link': 'https://finance.yahoo.com/m/56723767-0234-3bc4-af3a-106f23b2e505/virgin-galactic-to-launch.html',
  'providerPublishTime': 1688039400,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/EC9xSQXt5xlE1Y9d4sAraQ--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/wsj.com/44a097aa6288ec93b4211ad352ea38f2',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/UviI2HOplxIteI2T06YRrA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/wsj.com/44a097aa6288ec93b4211ad352ea38f2',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}},
 {'uuid': '64e016cc-6c1c-33b8-95b4-af656e162c57',
  'title': 'Will a "Super App" Strategy Send Coinbase Stock Soaring?',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/64e016cc-6c1c-33b8-95b4-af656e162c57/will-a-%22super-app%22-strategy.html',
  'providerPublishTime': 1688039400,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/cf3g06jwj7FM0J3xcyjlbA--~B/aD0xNDE0O3c9MjEyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/5a7bfe9a202a6597ff311c9c17b6ed24',
     'width': 2120,
     'height': 1414,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/NcwbCpDfczrXpnVFkoWHXw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/5a7bfe9a202a6597ff311c9c17b6ed24',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['COIN']},
 {'uuid': '7be0fb80-8d6c-3eb7-82ed-7815f3d809de',
  'title': 'VIN Foundation Announces 7th Annual Solutions for the Profession Competition Winners',
  'publisher': 'PR Newswire',
  'link': 'https://finance.yahoo.com/news/vin-foundation-announces-7th-annual-115000666.html',
  'providerPublishTime': 1688039400,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ny3yhf3ythEPWKveLoIh2g--~B/aD0xNjt3PTE2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/prnewswire.com/5d567a6aa0d1664619f809929ca55a10',
     'width': 16,
     'height': 16,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/IIwtQDwl.mFrte9_xPDx.A--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/prnewswire.com/5d567a6aa0d1664619f809929ca55a10',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}},
 {'uuid': '84e5c628-5765-32bb-b0ad-97b31ac63acd',
  'title': 'Genius Metals Acquires a 100% interest in the Paka property located in James Bay, Québec',
  'publisher': 'CNW Group',
  'link': 'https://finance.yahoo.com/news/genius-metals-acquires-100-interest-115000260.html',
  'providerPublishTime': 1688039400,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Rs.NZ0yYsYSbnq5CH.OKIw--~B/aD0xNTY7dz0zMTI7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/cnwgroup.com/70c4d94042c5f279dabcb9e2530c0eb5',
     'width': 312,
     'height': 156,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/kCi30heQqxG1REypQCegiw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/cnwgroup.com/70c4d94042c5f279dabcb9e2530c0eb5',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['GNSMF']}]

In [29]:
# income statement
msft.financials

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Tax Effect Of Unusual Items,-1477278.132129,673230.479018,-1276355.285707,-990785.357064
Tax Rate For Calcs,0.216103,0.180346,0.143025,0.147878
Normalized EBITDA,316380000.0,381251000.0,391559000.0,373541000.0
Total Unusual Items,-6836000.0,3733000.0,-8924000.0,-6700000.0
Total Unusual Items Excluding Goodwill,-6836000.0,3733000.0,-8924000.0,-6700000.0
Net Income From Continuing Operation Net Minority Interest,114420000.0,173370000.0,175020000.0,181121000.0
Reconciled Depreciation,141790000.0,151955000.0,151911000.0,131850000.0
Reconciled Cost Of Revenue,318425000.0,325478000.0,299245000.0,264480000.0
EBIT,167754000.0,233029000.0,230724000.0,234991000.0
Net Interest Income,-18716000.0,-25403000.0,-30121000.0,-25213000.0
Interest Expense,21791000.0,21513000.0,26494000.0,22438000.0
Interest Income,2860000.0,1170000.0,1302000.0,2097000.0
Normalized Income,119778721.867871,170310230.479018,182667644.714293,186830214.642936
Net Income From Continuing And Discontinued Operation,114420000.0,173370000.0,175020000.0,181121000.0
Total Expenses,786243000.0,728918000.0,653758000.0,736550000.0
Rent Expense Supplemental,NaN,NaN,NaN,8971000.0
Total Operating Income As Reported,163385000.0,238084000.0,233600000.0,235420000.0
Diluted Average Shares,71957000.0,72377000.0,73232000.0,73489000.0
Basic Average Shares,71673000.0,71725000.0,71988000.0,70392000.0
Diluted EPS,1.59,2.4,2.39,2.46
Basic EPS,1.6,2.42,2.43,2.57
Diluted NI Availto Com Stockholders,114420000.0,173370000.0,175020000.0,181121000.0
Net Income Common Stockholders,114420000.0,173370000.0,175020000.0,181121000.0
Otherunder Preferred Stock Dividend,0.0,0.0,0.0,0.0
Net Income,114420000.0,173370000.0,175020000.0,181121000.0
Minority Interests,NaN,NaN,0.0,0.0
Net Income Including Noncontrolling Interests,114420000.0,173370000.0,175020000.0,181121000.0
Net Income Continuous Operations,114420000.0,173370000.0,175020000.0,181121000.0
Tax Provision,31543000.0,38146000.0,29210000.0,31432000.0
Pretax Income,145963000.0,211516000.0,204230000.0,212553000.0
Net Non Operating Interest Income Expense,-18716000.0,-25403000.0,-30121000.0,-25213000.0
Total Other Finance Cost,-215000.0,5060000.0,4929000.0,4872000.0
Interest Expense Non Operating,21791000.0,21513000.0,26494000.0,22438000.0
Interest Income Non Operating,2860000.0,1170000.0,1302000.0,2097000.0
Operating Income,163385000.0,238084000.0,233600000.0,235420000.0
Operating Expense,467818000.0,403440000.0,354513000.0,472070000.0
Other Operating Expenses,178239000.0,149759000.0,148582000.0,194869000.0
Selling General And Administration,289579000.0,253681000.0,205931000.0,277201000.0
Selling And Marketing Expense,202765000.0,163923000.0,135896000.0,177449000.0
General And Administrative Expense,86814000.0,89758000.0,70035000.0,99752000.0
Gross Profit,631203000.0,641524000.0,588113000.0,707490000.0
Cost Of Revenue,318425000.0,325478000.0,299245000.0,264480000.0
Total Revenue,949628000.0,967002000.0,887358000.0,971970000.0
Operating Revenue,949628000.0,967002000.0,887358000.0,971970000.0

In [19]:
# retrive Gross profit,Cost of revenue,Operating expenses,Operating income,Net income
msft.financials.loc[['Gross Profit','Cost Of Revenue','Total Revenue','Operating Revenue']]

                    2022-12-31   2021-12-31   2020-12-31   2019-12-31
Gross Profit       631203000.0  641524000.0  588113000.0  707490000.0
Cost Of Revenue    318425000.0  325478000.0  299245000.0  264480000.0
Total Revenue      949628000.0  967002000.0  887358000.0  971970000.0
Operating Revenue  949628000.0  967002000.0  887358000.0  971970000.0

In [30]:
data

                  Open        High         Low       Close   Adj Close  Volume
Date
2020-01-03  153.100006  154.000000  151.550003  153.600006  147.812164  274068
2020-01-06  152.350006  153.300003  151.100006  153.300003  147.523468  225145
2020-01-07  153.850006  156.500000  151.500000  151.500000  145.791321  268437
2020-01-08  151.100006  153.000000  149.500000  152.850006  147.090439  245846
2020-01-09  154.000000  155.949997  152.800003  155.149994  149.303757  280922
...                ...         ...         ...         ...         ...     ...
2023-06-21   71.139999   71.540001   69.820000   70.260002   70.260002  215430
2023-06-22   69.860001   70.260002   69.459999   70.180000   70.180000  124855
2023-06-23   69.820000   70.099998   68.680000   69.160004   69.160004  168352
2023-06-26   69.000000   69.639999   67.980003   68.720001   68.720001  207825
2023-06-27   69.080002   69.120003   68.260002   68.559998   68.559998  112393

[881 rows x 6 columns]

In [40]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


# Select features and target variable
features = data[['Open', 'High', 'Low', 'Volume']]
target = data['Close']

In [41]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [42]:
# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [45]:
# Make predictions on the test data
y_pred = model.predict(X_test)

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)

In [46]:
mse

1.3481945387198893

In [47]:
import yfinance as yf

# Define the ticker symbol for the stock you want to fetch data for
ticker_symbol = "ORCL"

# Fetch historical stock price data
data2 = yf.download(ticker_symbol, start="2020-01-01", end="2023-06-28")

[*********************100%***********************]  1 of 1 completed

In [48]:
#test the model with ORCL
features2 = data2[['Open', 'High', 'Low', 'Volume']]
target2 = data2['Close']

# Make predictions on the test data
y_pred2 = model.predict(features2)

# Calculate mean squared error
mse2 = mean_squared_error(target2, y_pred2)

In [49]:
mse2

3.092017510774372

### define function for researching

In [2]:
def ticker_data(ticker_symbol):
    ticker_data = yf.download(ticker_symbol, start="2020-01-01", end="2023-06-28")
    return ticker_data

In [31]:
import yfinance as yf
import pandas as pd

def save_financial_data(ticker):
    stock = yf.Ticker(ticker)
    
    # Get income statement for the current year
    income_stmt = stock.get_income_stmt()
    
    # Filter columns for the previous year
    current_year = income_stmt.columns[0].year
    prev_year_income_stmt = income_stmt.iloc[:, income_stmt.columns.year == current_year - 1]
    
    # Get balance sheet for the current year
    balance_sheet = stock.balance_sheet

        
    # Filter columns for the previous year
    prev_year_balance_sheet = balance_sheet.iloc[:, balance_sheet.columns.year == current_year - 1]
    

    # Get cash flow statement for the current year
    cash_flow_stmt = stock.cashflow

    # Filter columns for the previous year
    prev_year_cash_flow_stmt = cash_flow_stmt.iloc[:, cash_flow_stmt.columns.year == current_year - 1]

    # Save income statement as Excel file
    income_stmt_file = f"{ticker}_income_statement.xlsx"
    with pd.ExcelWriter(income_stmt_file) as writer:
        income_stmt.to_excel(writer, sheet_name='Current Year')
        prev_year_income_stmt.to_excel(writer, sheet_name='Previous Year')
    
    # Save balance sheet as Excel file
    balance_sheet_file = f"{ticker}_balance_sheet.xlsx"
    with pd.ExcelWriter(balance_sheet_file) as writer:
        balance_sheet.to_excel(writer, sheet_name='Current Year')
        prev_year_balance_sheet.to_excel(writer, sheet_name='Previous Year')


    # Save cash flow statement as Excel file
    cash_flow_stmt_file = f"{ticker}_cash_flow_statement.xlsx"
    with pd.ExcelWriter(cash_flow_stmt_file) as writer:
        cash_flow_stmt.to_excel(writer, sheet_name='Current Year')
        prev_year_cash_flow_stmt.to_excel(writer, sheet_name='Previous Year')
    
    print(f"Income statement saved as {income_stmt_file}")
    print(f"Balance sheet saved as {balance_sheet_file}")
    print(f"Cash flow statement saved as {cash_flow_stmt_file}")
    
# Example usage
ticker_symbol = "TEMN.SW"
save_financial_data(ticker_symbol)

Income statement saved as TEMN.SW_income_statement.xlsx
Balance sheet saved as TEMN.SW_balance_sheet.xlsx
Cash flow statement saved as TEMN.SW_cash_flow_statement.xlsx

In [32]:
df2=pd.read_excel("/home/jacky/AI_predict_Stock/TEMN.SW_balance_sheet.xlsx",sheet_name='Current Year',index_col=0)
df2

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Treasury Shares Number,3164632.0,3164632.0,1804267.0,1.804267e+06
Ordinary Shares Number,71771128.0,71577636.0,72401999.0,7.095320e+07
Share Issued,74935760.0,74742268.0,74206266.0,7.275747e+07
Net Debt,711963000.0,776320000.0,819505000.0,9.704640e+08
Total Debt,840803000.0,959858000.0,977856000.0,1.174567e+09
...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,125035000.0,146078000.0,110195000.0,1.572160e+08
Other Short Term Investments,35112000.0,6756000.0,NaN,4.431000e+06
Cash And Cash Equivalents,89923000.0,139322000.0,110195000.0,1.527850e+08
Cash Equivalents,20098000.0,37500000.0,22776000.0,5.071500e+07
Cash Financial,69825000.0,101822000.0,87419000.0,1.020700e+08

In [33]:
df=pd.read_excel("/home/jacky/AI_predict_Stock/TEMN.SW_balance_sheet.xlsx",sheet_name='Current Year',index_col=0)

In [34]:
df3=pd.read_excel("/home/jacky/AI_predict_Stock/TEMN.SW_cash_flow_statement.xlsx",sheet_name='Current Year',index_col=0)
df3

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
Free Cash Flow,192875000.0,358011000.0,296881000.0,268424000.0
Repurchase Of Capital Stock,0.0,-200170000.0,NaN,0.0
Repayment Of Debt,-502625000.0,-327000000.0,-424243000.0,-531682000.0
Issuance Of Debt,405294000.0,342902000.0,153407000.0,826684000.0
Capital Expenditure,-105032000.0,-102118000.0,-86078000.0,-78630000.0
End Cash Position,89923000.0,139322000.0,110195000.0,152785000.0
Beginning Cash Position,139322000.0,110195000.0,152785000.0,287439000.0
Effect Of Exchange Rate Changes,-2210000.0,-3511000.0,3479000.0,789000.0
Changes In Cash,-47189000.0,32638000.0,-46069000.0,-135443000.0
Financing Cash Flow,-207972000.0,-295965000.0,-381286000.0,198803000.0
Net Other Financing Charges,6104000.0,NaN,-4162000.0,-5835000.0
Interest Paid Cff,-22581000.0,-19680000.0,-23487000.0,-21714000.0
Cash Dividends Paid,-74405000.0,-71427000.0,-63355000.0,-52361000.0
Common Stock Dividend Paid,NaN,NaN,-63355000.0,-52361000.0
Net Common Stock Issuance,0.0,-200170000.0,NaN,0.0
Common Stock Payments,0.0,-200170000.0,NaN,0.0
Net Issuance Payments Of Debt,-97331000.0,15902000.0,-270836000.0,295002000.0
Net Long Term Debt Issuance,-97331000.0,15902000.0,-270836000.0,295002000.0
Long Term Debt Payments,-502625000.0,-327000000.0,-424243000.0,-531682000.0
Long Term Debt Issuance,405294000.0,342902000.0,153407000.0,826684000.0
Investing Cash Flow,-137124000.0,-131526000.0,-47742000.0,-681300000.0
Net Other Investing Changes,NaN,NaN,21000000.0,-21000000.0
Interest Received Cfi,384000.0,247000.0,996000.0,1234000.0
Net Investment Purchase And Sale,-5775000.0,-8129000.0,7425000.0,-10173000.0
Sale Of Investment,NaN,0.0,14052000.0,NaN
Purchase Of Investment,-5775000.0,-8129000.0,-6627000.0,-10173000.0
Net Business Purchase And Sale,-1000000.0,-1670000.0,2848000.0,-573089000.0
Sale Of Business,NaN,NaN,2848000.0,NaN
Purchase Of Business,-1000000.0,-1670000.0,NaN,-573089000.0
Net Intangibles Purchase And Sale,-2331000.0,-3434000.0,-2829000.0,-68641000.0
Purchase Of Intangibles,-2331000.0,-3434000.0,-2829000.0,-68641000.0
Net PPE Purchase And Sale,-16283000.0,-8113000.0,-6867000.0,-9631000.0
Sale Of PPE,77000.0,44000.0,67000.0,358000.0
Purchase Of PPE,-16360000.0,-8157000.0,-6934000.0,-9989000.0
Capital Expenditure Reported,-86341000.0,-90527000.0,-76315000.0,-68641000.0
Operating Cash Flow,297907000.0,460129000.0,382959000.0,347054000.0
Taxes Refund Paid,-18718000.0,-12834000.0,-23236000.0,-17197000.0
Change In Working Capital,-40986000.0,38273000.0,33411000.0,-42494000.0
Change In Other Current Assets,33829000.0,49300000.0,57996000.0,5716000.0
Change In Payable,-16062000.0,48611000.0,-72101000.0,9269000.0
Change In Receivables,-58753000.0,-59638000.0,47516000.0,-57479000.0
Other Non Cash Items,25838000.0,27468000.0,12534000.0,26079000.0
Stock Based Compensation,52701000.0,44855000.0,6325000.0,39463000.0
Depreciation And Amortization,141790000.0,151955000.0,151911000.0,131850000.0
Depreciation,141790000.0,151955000.0,151911000.0,131850000.0
Gain Loss On Investment Securities,36000.0,-3733000.0,8924000.0,6700000.0
Net Foreign Currency Exchange Gain Loss,-8877000.0,2564000.0,-11241000.0,-10179000.0
Gain Loss On Sale Of PPE,160000.0,65000.0,101000.0,279000.0
Net Income From Continuing Operations,145963000.0,211516000.0,204230000.0,212553000.0

In [38]:

# Calculate the ratios
df.loc['Debt to Equity Ratio'] = df.loc['Total Debt'] / df.loc['Stockholders Equity']
df.loc['Quick Ratio'] = (df.loc['Cash And Cash Equivalents'] + df.loc['Other Short Term Investments']) / df.loc['Current Liabilities']
df.loc['Current Ratio'] = df.loc['Current Assets'] / df.loc['Current Liabilities']
df.loc['Revenue Growth Rate'] = (df.loc['Total Capitalization'] - df.shift(1).loc['Total Capitalization']) / df.shift(1).loc['Total Capitalization']
df.loc['Cash Flow rate']= df3.loc['Operating Cash Flow']/df2.loc['Total Debt']

In [41]:
#create a new dataframe with ratio calculation
df_ratio=df.loc[['Debt to Equity Ratio','Quick Ratio','Current Ratio','Revenue Growth Rate','Cash Flow rate']]
df_ratio

# save it as a new excel file
df_ratio.to_excel("/home/jacky/AI_predict_Stock/TEMN.SW_ratio.xlsx")

In [3]:
import pandas as pd
df4=pd.read_excel("/home/jacky/AI_predict_Stock/TEMN.SW_ratio.xlsx", index_col=0)
df4

                      2022-12-31  2021-12-31  2020-12-31  2019-12-31
Debt to Equity Ratio    1.520318    2.021656    1.868259    2.639002
Quick Ratio             0.135983    0.167362         NaN    0.233189
Current Ratio           0.476902    0.548283    0.738891    0.803087
Revenue Growth Rate     1.102827    1.514545    1.766561    2.333549
Cash Flow rate          0.354312    0.479372    0.391631    0.295474